name: project_badanvv
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1
  persian_datetime_picker: ^2.6.0
  hive_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:




flutter:

  
  uses-material-design: true

  
  assets:
     - assets/translations/
     - assets/icons/
    

  
  fonts:
    - family: Arianfonts1
      fonts:
        - asset: assets\fonts\en\gilroy_bold.otf
          weight: 700
        - asset: assets\fonts\en\gilroy_regular.otf
          weight: 400
          
    - family: Arianfonts2
      fonts:
        - asset: assets\fonts\fa\yekan_bakh_bold.ttf
          weight: 700
        - asset: assets\fonts\fa\yekan_bakh_regular.ttf
          weight: 400
  

